import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { generateRecipes } from '../scripts/generate-recipes.js';
import { generateToolDocs } from '../scripts/generate-tool-docs.js';
import { apply } from '../scripts/lib/generate.js';
import { TOOL_NAMES } from '../src/tools/definitions.js';
import { COMPOSITE_TOOL_NAMES } from '../src/tools/composite.js';

/**
 * The drift check.
 *
 * CI runs `npm run docs:check` as well, which is the gate that matters. This
 * runs the same comparison inside `npm test` so the failure arrives while you
 * are still holding the change, rather than five minutes later in a pipeline.
 *
 * A schema edit with no regenerated page fails here. That is the entire point
 * of generating the reference from the running server: documentation cannot
 * be left stale, because leaving it stale breaks the build.
 */

const DOCS = join(import.meta.dirname, '..', 'docs');

describe('generated documentation', () => {
  it('matches what is committed', async () => {
    const files = [...(await generateToolDocs()), ...(await generateRecipes())];
    const result = await apply(files, 'check');

    expect(
      { missing: result.missing, drifted: result.drifted },
      'Run `npm run docs:generate` and commit the result.'
    ).toEqual({ missing: [], drifted: [] });
  });

  it('has a page for every registered tool and nothing else', async () => {
    const pages = (await readdir(join(DOCS, 'tools')))
      .filter((name) => name.endsWith('.md') && name !== 'README.md')
      .map((name) => name.replace(/\.md$/, ''))
      .sort();

    expect(pages).toEqual([...TOOL_NAMES, ...COMPOSITE_TOOL_NAMES].sort());
  });

  it('warns against editing the generated pages by hand', async () => {
    for (const directory of ['tools', 'recipes']) {
      for (const name of await readdir(join(DOCS, directory))) {
        if (!name.endsWith('.md')) continue;
        const contents = await readFile(join(DOCS, directory, name), 'utf8');
        expect(contents.startsWith('<!-- Generated by'), `${directory}/${name}`).toBe(true);
      }
    }
  });

  it('states in every recipe that the underlying data is fixture data', async () => {
    // These pages show real output from real code against invented companies.
    // A reader who mistakes the second half for real companies has been
    // misled, so the caveat is asserted rather than trusted to survive edits.
    for (const name of await readdir(join(DOCS, 'recipes'))) {
      if (!name.endsWith('.md') || name === 'README.md') continue;
      const contents = await readFile(join(DOCS, 'recipes', name), 'utf8');
      expect(contents, name).toContain('the companies are invented');
    }
  });

  it('does not document a rating anywhere', async () => {
    // ADR 7. If a score is ever added, this fails and whoever added it has to
    // read the reasoning before deleting the test.
    // Collapsed, because markdown line wrapping should not decide whether an
    // assertion about the content passes.
    const index = (await readFile(join(DOCS, 'tools', 'README.md'), 'utf8')).replace(/\s+/g, ' ');
    expect(index).toContain('no score, grade or traffic light');
    expect(index).toContain('adr/0007-signals-not-scores.md');
  });
});
