import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { generateRecipes } from '../scripts/generate-recipes.js';
import { generateToolDocs } from '../scripts/generate-tool-docs.js';
import { apply } from '../scripts/lib/generate.js';
import { TOOL_NAMES } from '../src/tools/definitions.js';
import { COMPOSITE_TOOL_NAMES } from '../src/tools/composite.js';

/**
 * The drift check.
 *
 * CI runs `npm run docs:check` as well, which is the gate that matters. This
 * runs the same comparison inside `npm test` so the failure arrives while you
 * are still holding the change, rather than five minutes later in a pipeline.
 *
 * A schema edit with no regenerated page fails here. That is the entire point
 * of generating the reference from the running server: documentation cannot
 * be left stale, because leaving it stale breaks the build.
 */

const DOCS = join(import.meta.dirname, '..', 'docs');

describe('generated documentation', () => {
  it('matches what is committed', async () => {
    const files = [...(await generateToolDocs()), ...(await generateRecipes())];
    const result = await apply(files, 'check');

    expect(
      { missing: result.missing, drifted: result.drifted },
      'Run `npm run docs:generate` and commit the result.'
    ).toEqual({ missing: [], drifted: [] });
  });

  it('has a page for every registered tool and nothing else', async () => {
    const pages = (await readdir(join(DOCS, 'tools')))
      .filter((name) => name.endsWith('.md') && name !== 'README.md')
      .map((name) => name.replace(/\.md$/, ''))
      .sort();

    expect(pages).toEqual([...TOOL_NAMES, ...COMPOSITE_TOOL_NAMES].sort());
  });

  it('warns against editing the generated pages by hand', async () => {
    for (const directory of ['tools', 'recipes']) {
      for (const name of await readdir(join(DOCS, directory))) {
        if (!name.endsWith('.md')) continue;
        const contents = await readFile(join(DOCS, directory, name), 'utf8');
        expect(contents.startsWith('<!-- Generated by'), `${directory}/${name}`).toBe(true);
      }
    }
  });

  it('disclaims any assertion about the real companies it names', async () => {
    // These pages name real companies and real officers. The data is public
    // record under the Open Government Licence, but the framing around it is
    // ours, and a reader must not come away thinking the project is making a
    // claim about anybody. The disclaimer is asserted rather than trusted to
    // survive an edit.
    //
    // This assertion previously required the words "the companies are
    // invented", which stopped being true the day the fixtures were recorded
    // from the live API — and it failed, which is exactly what it was for.
    for (const name of await readdir(join(DOCS, 'recipes'))) {
      if (!name.endsWith('.md')) continue;
      // Collapse the blockquote markers too — the disclaimer is inside a `>`
      // block, and `>` is not whitespace, so it survives a naive collapse and
      // lands in the middle of the sentence being matched.
      const contents = (await readFile(join(DOCS, 'recipes', name), 'utf8')).replace(/[\s>]+/g, ' ');
      expect(contents, name).toContain('Open Government Licence');
      expect(contents, name).toMatch(/no claim about any company or person|Nothing here asserts anything about them/);
    }
  });

  it('does not document a rating anywhere', async () => {
    // ADR 7. If a score is ever added, this fails and whoever added it has to
    // read the reasoning before deleting the test.
    // Collapsed, because markdown line wrapping should not decide whether an
    // assertion about the content passes.
    const index = (await readFile(join(DOCS, 'tools', 'README.md'), 'utf8')).replace(/\s+/g, ' ');
    expect(index).toContain('no score, grade or traffic light');
    expect(index).toContain('adr/0007-signals-not-scores.md');
  });
});
