import { readFile, writeFile } from 'node:fs/promises';

/**
 * Shared plumbing for the documentation generators.
 *
 * Both generators run in two modes. `write` regenerates the files; `check`
 * regenerates in memory and reports anything that differs from what is
 * committed, without touching the working tree. CI runs `check`, which is
 * what makes the documentation impossible to leave stale: a schema change
 * with no regenerated page fails the build.
 */

export type Mode = 'write' | 'check';

export interface GeneratedFile {
  path: string;
  contents: string;
}

export const GENERATED_BANNER =
  '<!-- Generated by `npm run docs:generate`. Do not edit by hand: CI regenerates this file and fails the build if it differs. -->';

/** Normalises line endings so a Windows checkout does not report false drift. */
const normalise = (value: string): string => value.replace(/\r\n/g, '\n');

export interface ApplyResult {
  written: string[];
  drifted: string[];
  missing: string[];
}

export async function apply(files: GeneratedFile[], mode: Mode): Promise<ApplyResult> {
  const result: ApplyResult = { written: [], drifted: [], missing: [] };

  for (const file of files) {
    let existing: string | undefined;
    try {
      existing = normalise(await readFile(file.path, 'utf8'));
    } catch {
      existing = undefined;
    }

    const next = normalise(file.contents);

    if (mode === 'write') {
      if (existing !== next) {
        await writeFile(file.path, next, 'utf8');
        result.written.push(file.path);
      }
      continue;
    }

    if (existing === undefined) result.missing.push(file.path);
    else if (existing !== next) result.drifted.push(file.path);
  }

  return result;
}

export function reportAndExit(result: ApplyResult, mode: Mode, label: string): void {
  if (mode === 'write') {
    process.stdout.write(
      result.written.length === 0
        ? `${label}: already up to date.\n`
        : `${label}: wrote ${result.written.length} file(s).\n${result.written.map((path) => `  ${path}\n`).join('')}`
    );
    return;
  }

  const problems = [...result.missing, ...result.drifted];
  if (problems.length === 0) {
    process.stdout.write(`${label}: up to date.\n`);
    return;
  }

  process.stderr.write(
    `${label} is out of date. Run \`npm run docs:generate\` and commit the result.\n\n` +
      result.missing.map((path) => `  missing: ${path}\n`).join('') +
      result.drifted.map((path) => `  changed: ${path}\n`).join('')
  );
  process.exitCode = 1;
}

export function parseMode(argv: string[]): Mode {
  return argv.includes('--check') ? 'check' : 'write';
}
